# Generated by Django 5.1.5 on 2025-02-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_userprofile_email_userprofile_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
